Feature/view/user/detail
team-yeolmae/challenge pull request #63
Opened 2024-03-06 03:54 UTC by LeeHanJo

## 기능 요약
view 전체목록 상세페이지 화면 출력

## 주요 작업 내용
-  전체목록과 인기목록으로 나누어서 컨트롤러 수정, 로고 추가 
- PageRequest1DTO(인기목록) 와 PageRequest1DTO(인기목록) 추가

## 비고(To Reviewers :pray:)
- 고칠부분 말씀해주세요.

2024-03-06 04:12 UTC, thdrkfka requested changes

2024-03-06 04:12 UTC, thdrkfka commented on src/main/resources/application.yml
yml 파일 삭제 부탁드립니다!

2024-03-06 04:12 UTC, thdrkfka commented on src/main/resources/static/css/styles1.css
css 파일 2개가 있어서 styles1.css 는 삭제해도 될 것 같습니다!

2024-03-06 05:26 UTC, austenlove approved these changes

2024-03-08 03:09 UTC, thdrkfka approved these changes

2024-03-08 03:18 UTC, austenlove approved these changes

2024-03-08 08:46 UTC, thdrkfka approved these changes

2024-03-08 08:52 UTC, thdrkfka approved these changes

2024-03-08 08:52 UTC, merged